config/routes.rb
require 'api_version_control'

Rails.application.routes.draw do
  resources :todo_lists
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  namespace :api, defaults: { format: :json }, path: '/' do
    namespace :v1, path: "/v1", constraints: ApiVersionControl.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :sessions, only: [:create, :destroy]
      resources :projects, only: [:index] do
        resources :todo_lists, only: [:index, :update, :show]
      end
    end
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :project
  validates :description, :project_id, presence: true
  validates_associated :project

  after_save :touch_project

  protected

  def touch_project
    self.project.touch
  end
end

app/controllers/api/v1/todo_lists_controller.rb
class Api::V1::TodoListsController < Api::V1::BaseController
  before_action :authenticate_with_token!
  before_action :set_todo_list, only: [:update]

  def index
    render json: current_user.todo_lists.where(project_id: params[:project_id]), status: 200
  end

  def update
    begin
      @todo_list.update(todo_list_params)
      render json: @todo_list, status: 200
    rescue => exception
      head 401
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      begin
        @todo_list = current_user.todo_lists.where(project_id: params[:project_id]).find(params[:id])
      rescue => exception
        head 401
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:is_checked)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(:page => params[:page]).order(:scheduled_to)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Lista de Tarefas criada com sucesso.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Lista de Tarefas atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'A Lista de Tarefa foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:project_id, :description, :scheduled_to, :is_checked)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
	def todo_list_is_checked?(is_checked = false)
		is_checked ? t('simple_form.yes') : t('simple_form.no')
	end
end

app/views/todo_lists/_form.html.erb
<%= simple_form_for(@todo_list) do |form| %>

  <div class="form-inputs">
    <%= form.association :project, collection: current_user.projects %>
    <%= form.input :description %>
    <%= form.input :is_checked %>
    <%= form.input :scheduled_to %>
  </div>

  <div class="form-actions">
    <%= form.submit 'Salvar', class: 'btn btn-primary btn-sm' %>
    <%= link_to('Detalhes', todo_list, class: 'btn btn-info btn-sm') unless todo_list.new_record? %>
    <%= link_to 'Cancelar', todo_lists_path, class: 'btn btn-info btn-sm' %>
  </div>
<% end %>

app/views/todo_lists/_todo_lists.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Projeto</th>
        <th>Cód.</th>
        <th>Descrição</th>
        <th>Realizada?</th>
        <th>Agendada para</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% todo_lists.each do |todo_list| %>
        <tr>
          <td><%= todo_list.project_id %> - <%= truncate todo_list.project.title, length: 20 %></td>
          <td><%= todo_list.id %></td>
          <td><%= truncate todo_list.description, length: 20 %></td>
          <td><%= todo_list_is_checked?(todo_list.is_checked) %></td>
          <td><%= l todo_list.scheduled_to, format: :short %></td>
          <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="...">
              <%= link_to 'Detalhes', todo_list, class: 'btn btn-info btn-sm' %>
              <%= link_to 'Editar', edit_todo_list_path(todo_list), class: 'btn btn-info btn-sm' %>
              <%= link_to 'Apagar', todo_list, method: :delete, data: { confirm: 'Deseja continuar com esta ação? Ela não poderá ser desfeita.' }, class: 'btn btn-danger btn-sm' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
	<% if todo_lists.total_entries > 15 %>
	<div class="apple_pagination">
		<%= will_paginate todo_lists, :page_links => false %>
	</div>
	<% end %>
</div>

app/views/todo_lists/edit.html.erb
<h1>Alteração da Lista de Tarefas</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h1 class="h2">Lista de Tarefas</h1>
</div>

<%= render partial: "todo_lists", locals: {todo_lists: @todo_lists} %>

<br />

<%= link_to 'Criar Tarefa', new_todo_list_path, class: 'btn btn-primary btn-sm' %>

app/views/todo_lists/new.html.erb
<h1>Criando uma Tarefa</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/show.html.erb
<h3>Dados da Lista de Tarefas</h3>

<p>
  <strong>Projeto:</strong>
  <%= @todo_list.project %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @todo_list.description %>
</p>

<p>
  <strong>Realizada?:</strong>
  <%= todo_list_is_checked?(@todo_list.is_checked) %>
</p>

<p>
  <strong>Agendada para:</strong>
  <%= l @todo_list.scheduled_to %>
</p>

<p>
  <strong>Data da Criação:</strong>
  <%= l @todo_list.created_at %>
</p>

<%= link_to 'Atualizar', edit_todo_list_path(@todo_list), class: 'btn btn-primary btn-sm' %> |
<%= link_to 'Voltar', todo_lists_path, class: 'btn btn-info btn-sm' %>