config/routes.rb
require 'api_version_control'

Rails.application.routes.draw do
  resources :todo_lists
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  namespace :api, defaults: { format: :json }, path: '/' do
    namespace :v1, path: "/v1", constraints: ApiVersionControl.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :sessions, only: [:create, :destroy]
      resources :projects, only: [:index] do
        resources :todo_lists, only: [:index, :update, :show]
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :todo_lists
  validates :title, presence: true

  attr_accessor :count_todo_lists, :todo_lists_evaluation

  def todo_lists_checkeds
    todo_lists.where('is_checked = ? ', true)
  end

  def todo_lists_not_checkeds
    todo_lists.where('(is_checked = ? OR is_checked IS NULL)', false)
  end

  def to_s
    title
  end

  def count_todo_lists
    self.todo_lists.count
  end

  def todo_lists_evaluation
    total_done = self.count_todo_lists
    total_in_progress = self.todo_lists.where(is_checked: true).count
    total = (total_done / total_in_progress.to_f).to_f
    if total == 1.0
      1.0
    elsif total_in_progress == 0
      0.25
    else
      total_in_progress/10.0
    end
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_action :authenticate_with_token!
  before_action :set_project, only: :todo_lists

  def index
    render json: current_user.projects.to_json(methods: [:count_todo_lists, :todo_lists_evaluation]), status: 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      begin
        @project = current_user.projects.find(params[:id])
      rescue => exception
        head 401
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.paginate(:page => params[:page]).order("updated_at DESC")
    @projects = @projects.where("title ilike ?", "%#{params[:search]}%") unless params[:search].blank?
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projeto criado com sucesso.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projeto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'O Projeto foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      begin
        @project = current_user.projects.find(params[:id])
      rescue => exception
        redirect_to root_path, notice: 'Este projeto não lhe pertence'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(project, local: true) do |form| %>
  <%= form.input :title %>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-primary btn-sm' %>
    <%= link_to('Detalhes', project, class: 'btn btn-info btn-sm') unless project.new_record? %>
    <%= link_to 'Cancelar', projects_path, class: 'btn btn-info btn-sm' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Alteração do Projeto</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
  <h1 class="h2">Lista de Projetos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Código</th>
        <th>Título</th>
        <th>Total de Tarefas</th>
        <th>Tarefas Realizadas</th>
        <th>Tarefas Não Realizadas</th>
        <th>Criação</th>
        <th>Atualização</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.id %></td>
          <td><%= truncate project.title %></td>
          <td><%= project.todo_lists.count %></td>
          <td><%= project.todo_lists_checkeds.count %></td>
          <td><%= project.todo_lists_not_checkeds.count %></td>
          <td><%= l project.created_at, format: :short %></td>
          <td><%= l project.updated_at, format: :short %></td>
          <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="...">
              <%= link_to 'Detalhes', project, class: 'btn btn-info btn-sm' %>
              <%= link_to 'Editar', edit_project_path(project), class: 'btn btn-info btn-sm' %>
              <%= link_to 'Apagar', project, method: :delete, data: { confirm: 'Deseja continuar com esta ação? Ela não poderá ser desfeita.' }, class: 'btn btn-danger btn-sm' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @projects.total_entries > 15 %>
	<div class="apple_pagination">
		<%= will_paginate @projects, :page_links => false %>
	</div>
  <% end %>
</div>

<br />

<%= link_to 'Criar Projeto', new_project_path, class: 'btn btn-primary btn-sm' %>

app/views/projects/new.html.erb
<h1>Criando um Projeto</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h3>Dados do Projeto</h3>

<p>
  <strong>Título:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Total de Tarefas:</strong>
  <%= @project.todo_lists.count %>
</p>

<p>
  <strong>Total de Tarefas Realizadas:</strong>
  <%= @project.todo_lists_checkeds.count %>
</p>


<p>
  <strong>Total de Tarefas Não Realizadas:</strong>
  <%= @project.todo_lists_not_checkeds.count %>
</p>


<p>
  <strong>Data da Criação:</strong>
  <%= l @project.created_at %>
</p>

<p>
  <strong>Última Atualização:</strong>
  <%= l @project.created_at %>
</p>

<%= link_to 'Atualizar', edit_project_path(@project), class: 'btn btn-primary btn-sm' %> |
<%= link_to 'Voltar', projects_path, class: 'btn btn-info btn-sm' %>
<br />
<br />

<h2>Tarefas</h2>

<%= render partial: "todo_lists/todo_lists", locals: {todo_lists: @project.todo_lists.paginate(page: params[:page], per_page: 15)} %>