config/routes.rb
require 'api_version_control'

Rails.application.routes.draw do
  resources :todo_lists
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  namespace :api, defaults: { format: :json }, path: '/' do
    namespace :v1, path: "/v1", constraints: ApiVersionControl.new(version: 1, default: true) do
      resources :users, only: [:index]
      resources :sessions, only: [:create, :destroy]
      resources :projects, only: [:index] do
        resources :todo_lists, only: [:index, :update, :show]
      end
    end
  end
end

app/views/layouts/_nav_bar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
	<div class="sidebar-sticky">
		<ul class="nav flex-column">
			<% if user_signed_in? %>
			<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
				<span>Olá, <%= truncate(current_user.name, length: 14) %></span>
				<a class="d-flex align-items-center text-muted" href="javascript:;">
					<span data-feather="plus-circle"></span>
				</a>
			</h6>
			<li class="nav-item">
				<%= link_to edit_user_registration_path, class: ['nav-link', current_page?(edit_user_registration_path) ? 'active' : nil].compact do%>
					<span data-feather="user-check"></span>
					Atualizar meus dados
				<% end %>
			</li>

			<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
				<span>Projetos</span>
				<a class="d-flex align-items-center text-muted" href="javascript:;">
					<span data-feather="plus-circle"></span>
				</a>
			</h6>
			<li class="nav-item">
				<%= link_to root_path, class: ['nav-link', current_page?(root_path) ? 'active' : nil].compact do%>
					<span data-feather="folder"></span>
					Lista de Projetos
				<% end %>
			</li>
			<li class="nav-item">
				<%= link_to new_project_path, class: ['nav-link', current_page?(new_project_path) ? 'active' : nil].compact do%>
					<span data-feather="folder-plus"></span>
					Criar projeto
				<% end %>
			</li>
		</ul>

		<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
			<span>Tarefas</span>
			<a class="d-flex align-items-center text-muted" href="javascript:;">
				<span data-feather="plus-circle"></span>
			</a>
		</h6>
		<ul class="nav flex-column mb-2">
			<li class="nav-item">
				<%= link_to todo_lists_path, class: ['nav-link', current_page?(todo_lists_path) ? 'active' : nil].compact do%>
					<span data-feather="list"></span>
					Lista de Tarefas
				<% end %>
			</li>
			<li class="nav-item">
				<%= link_to new_todo_list_path, class: ['nav-link', current_page?(new_todo_list_path) ? 'active' : nil].compact do%>
					<span data-feather="file-plus"></span>
					Criar Tarefa
				<% end %>
			</li>
			<% else %>
			<li class="nav-item">
				<%= link_to new_user_session_path, class: 'nav-link' do %>
					<span data-feather="log-in"></span>
					Entrar no Sistema
				<% end %>
			</li>
			<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
				<span>Ou melhor ainda</span>
				<%= link_to new_user_registration_path, class: 'd-flex align-items-center text-muted' do %>
					<span data-feather="plus-circle"></span>
				<% end %>
			</h6>
			<li class="nav-item">
				<%= link_to new_user_registration_path, class: 'nav-link' do %>
					<span data-feather="user-plus"></span>
					Faça seu registro
				<% end %>
			</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eAgro :: Projects</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <%= link_to 'eAgro :: Projects', root_path, class: 'navbar-brand col-sm-3 col-md-2 mr-0'%>
      <% if user_signed_in? %>
      <%= form_tag projects_path, method: :get, class: 'search_projects' do %>
      <input class="form-control form-control-dark w-100" name="search" type="text" placeholder="Buscar por projetos" aria-label="Buscar por projetos">
      <% end %>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <%= link_to 'Sair do Sistema', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
      <% end %>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <%= render "layouts/nav_bar" %>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <% if notice %>
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
          <% end %>

          <%= yield %>
        </main>
      </div>
    </div>
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>